FROM node:20-bookworm
ARG BUILD_SCRIPT=build-zkp-dev.sh
RUN apt-get update && apt-get install -y curl git && rm -rf /var/lib/apt/lists/*
RUN curl -L https://github.com/iden3/circom/releases/download/v2.1.9/circom-linux-amd64 \
  -o /usr/local/bin/circom && chmod +x /usr/local/bin/circom
RUN npm install -g snarkjs@0.7.5
WORKDIR /circuits
COPY circuits/ ./
RUN sed -i 's/\r$//' "$BUILD_SCRIPT" && chmod +x "$BUILD_SCRIPT" && ./"$BUILD_SCRIPT"
